<?xml version="1.0" encoding="utf-8"?><Database Name="SeProject" Class="DbHandlerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=SeProject;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SeProjectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Pid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="VendorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PImage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Vendor_Product" Member="Vendor" ThisKey="VendorId" OtherKey="Vid" Type="Vendor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vendor" Member="Vendors">
    <Type Name="Vendor">
      <Column Name="Vid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="VEmail" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="VPassword" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="VImage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Vendor_Product" Member="Products" ThisKey="Vid" OtherKey="VendorId" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Cid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UEmail" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UPassword" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CImage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>